### PR TITLE
Revert "feat: @ctrl/tinycolor treeshaking"

### PR DESCRIPTION
**Pull request by zombieJ**
Reverts ant-design/ant-design-colors#74

### CODE REVIEW

**Comment by steezeburger** [comment]
When will this be released?

**Comment by swillis12** [comment]
Need this as well. Will bump my AntD version as soon as it's released.

**Comment by steezeburger** [comment]
FWIW, I was able to use yarn resolutions to specify the proper version of @ant-design/colors to get our builds working again.

in my package.json:
```
"resolutions": {
    "**/@ant-design/colors": "5.0.1"
  },
```

**Comment by swillis12** [comment]
Thanks @steezeburger, I'm using npm so it's a little more convoluted last time I checked.

**Pull request merged**
